# Generated by Django 3.2.14 on 2022-07-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220721_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desciption',
            new_name='description',
        ),
    ]
